<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Surat;

class SuratSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $surats = [
            ['juz_id' => 1, 'nama_surat' => 'Al-Fatihah', 'mulai_ayat' => 1, 'akhir_ayat' => 7],
            ['juz_id' => 1, 'nama_surat' => 'Al-Baqarah', 'mulai_ayat' => 1, 'akhir_ayat' => 141],
            ['juz_id' => 2, 'nama_surat' => 'Al-Baqarah', 'mulai_ayat' => 142, 'akhir_ayat' => 252],
            ['juz_id' => 3, 'nama_surat' => 'Al-Baqarah', 'mulai_ayat' => 253, 'akhir_ayat' => 286],
            ['juz_id' => 3, 'nama_surat' => 'Ali \'Imran', 'mulai_ayat' => 1, 'akhir_ayat' => 91],
            ['juz_id' => 4, 'nama_surat' => 'Ali \'Imran', 'mulai_ayat' => 92, 'akhir_ayat' => 200],
            ['juz_id' => 4, 'nama_surat' => 'An-Nisa\'', 'mulai_ayat' => 1, 'akhir_ayat' => 23],
            ['juz_id' => 5, 'nama_surat' => 'An-Nisa\'', 'mulai_ayat' => 24, 'akhir_ayat' => 147],
            ['juz_id' => 6, 'nama_surat' => 'An-Nisa\'', 'mulai_ayat' => 148, 'akhir_ayat' => 176],
            ['juz_id' => 6, 'nama_surat' => 'Al-Ma\'idah', 'mulai_ayat' => 1, 'akhir_ayat' => 82],
            ['juz_id' => 7, 'nama_surat' => 'Al-Ma\'idah', 'mulai_ayat' => 83, 'akhir_ayat' => 120],
            ['juz_id' => 7, 'nama_surat' => 'Al-An\'am', 'mulai_ayat' => 1, 'akhir_ayat' => 110],
            ['juz_id' => 8, 'nama_surat' => 'Al-An\'am', 'mulai_ayat' => 111, 'akhir_ayat' => 165],
            ['juz_id' => 8, 'nama_surat' => 'Al-A\'raf', 'mulai_ayat' => 1, 'akhir_ayat' => 87],
            ['juz_id' => 9, 'nama_surat' => 'Al-A\'raf', 'mulai_ayat' => 88, 'akhir_ayat' => 206],
            ['juz_id' => 9, 'nama_surat' => 'Al-Anfal', 'mulai_ayat' => 1, 'akhir_ayat' => 40],
            ['juz_id' => 10, 'nama_surat' => 'Al-Anfal', 'mulai_ayat' => 41, 'akhir_ayat' => 75],
            ['juz_id' => 10, 'nama_surat' => 'At-Taubah', 'mulai_ayat' => 1, 'akhir_ayat' => 93],
            ['juz_id' => 11, 'nama_surat' => 'At-Taubah', 'mulai_ayat' => 94, 'akhir_ayat' => 129],
            ['juz_id' => 11, 'nama_surat' => 'Yunus', 'mulai_ayat' => 1, 'akhir_ayat' => 109],
            ['juz_id' => 12, 'nama_surat' => 'Hud', 'mulai_ayat' => 1, 'akhir_ayat' => 123],
            ['juz_id' => 12, 'nama_surat' => 'Yusuf', 'mulai_ayat' => 1, 'akhir_ayat' => 52],
            ['juz_id' => 13, 'nama_surat' => 'Yusuf', 'mulai_ayat' => 53, 'akhir_ayat' => 111],
            ['juz_id' => 13, 'nama_surat' => 'Ar-Ra\'d', 'mulai_ayat' => 1, 'akhir_ayat' => 43],
            ['juz_id' => 13, 'nama_surat' => 'Ibrahim', 'mulai_ayat' => 1, 'akhir_ayat' => 52],
            ['juz_id' => 14, 'nama_surat' => 'Al-Hijr', 'mulai_ayat' => 1, 'akhir_ayat' => 99],
            ['juz_id' => 14, 'nama_surat' => 'An-Nahl', 'mulai_ayat' => 1, 'akhir_ayat' => 128],
            ['juz_id' => 15, 'nama_surat' => 'Al-Isra\'', 'mulai_ayat' => 1, 'akhir_ayat' => 111],
            ['juz_id' => 15, 'nama_surat' => 'Al-Kahf', 'mulai_ayat' => 1, 'akhir_ayat' => 74],
            ['juz_id' => 16, 'nama_surat' => 'Al-Kahf', 'mulai_ayat' => 75, 'akhir_ayat' => 110],
            ['juz_id' => 16, 'nama_surat' => 'Maryam', 'mulai_ayat' => 1, 'akhir_ayat' => 98],
            ['juz_id' => 16, 'nama_surat' => 'Taha', 'mulai_ayat' => 1, 'akhir_ayat' => 135],
            ['juz_id' => 17, 'nama_surat' => 'Al-Anbiya\'', 'mulai_ayat' => 1, 'akhir_ayat' => 112],
            ['juz_id' => 17, 'nama_surat' => 'Al-Hajj', 'mulai_ayat' => 1, 'akhir_ayat' => 78],
            ['juz_id' => 18, 'nama_surat' => 'Al-Mu\'minun', 'mulai_ayat' => 1, 'akhir_ayat' => 118],
            ['juz_id' => 18, 'nama_surat' => 'An-Nur', 'mulai_ayat' => 1, 'akhir_ayat' => 64],
            ['juz_id' => 18, 'nama_surat' => 'Al-Furqan', 'mulai_ayat' => 1, 'akhir_ayat' => 20],
            ['juz_id' => 19, 'nama_surat' => 'Al-Furqan', 'mulai_ayat' => 21, 'akhir_ayat' => 77],
            ['juz_id' => 19, 'nama_surat' => 'Asy-Syu\'ara\'', 'mulai_ayat' => 1, 'akhir_ayat' => 227],
            ['juz_id' => 19, 'nama_surat' => 'An-Naml', 'mulai_ayat' => 1, 'akhir_ayat' => 55],
            ['juz_id' => 20, 'nama_surat' => 'An-Naml', 'mulai_ayat' => 56, 'akhir_ayat' => 93],
            ['juz_id' => 20, 'nama_surat' => 'Al-Qasas', 'mulai_ayat' => 1, 'akhir_ayat' => 88],
            ['juz_id' => 20, 'nama_surat' => 'Al-Ankabut', 'mulai_ayat' => 1, 'akhir_ayat' => 45],
            ['juz_id' => 21, 'nama_surat' => 'Al-Ankabut', 'mulai_ayat' => 46, 'akhir_ayat' => 69],
            ['juz_id' => 21, 'nama_surat' => 'Ar-Rum', 'mulai_ayat' => 1, 'akhir_ayat' => 60],
            ['juz_id' => 21, 'nama_surat' => 'Luqman', 'mulai_ayat' => 1, 'akhir_ayat' => 34],
            ['juz_id' => 21, 'nama_surat' => 'As-Sajdah', 'mulai_ayat' => 1, 'akhir_ayat' => 30],
            ['juz_id' => 21, 'nama_surat' => 'Al-Ahzab', 'mulai_ayat' => 1, 'akhir_ayat' => 30],
            ['juz_id' => 22, 'nama_surat' => 'Al-Ahzab', 'mulai_ayat' => 31, 'akhir_ayat' => 73],
            ['juz_id' => 22, 'nama_surat' => 'Saba\'', 'mulai_ayat' => 1, 'akhir_ayat' => 54],
            ['juz_id' => 22, 'nama_surat' => 'Fatir', 'mulai_ayat' => 1, 'akhir_ayat' => 45],
            ['juz_id' => 22, 'nama_surat' => 'Yasin', 'mulai_ayat' => 1, 'akhir_ayat' => 27],
            ['juz_id' => 23, 'nama_surat' => 'Yasin', 'mulai_ayat' => 28, 'akhir_ayat' => 83],
            ['juz_id' => 23, 'nama_surat' => 'Ash-Shaffat', 'mulai_ayat' => 1, 'akhir_ayat' => 182],
            ['juz_id' => 23, 'nama_surat' => 'Shad', 'mulai_ayat' => 1, 'akhir_ayat' => 88],
            ['juz_id' => 23, 'nama_surat' => 'Az-Zumar', 'mulai_ayat' => 1, 'akhir_ayat' => 31],
            ['juz_id' => 24, 'nama_surat' => 'Az-Zumar', 'mulai_ayat' => 32, 'akhir_ayat' => 75],
            ['juz_id' => 24, 'nama_surat' => 'Ghafir', 'mulai_ayat' => 1, 'akhir_ayat' => 85],
            ['juz_id' => 24, 'nama_surat' => 'Fushshilat', 'mulai_ayat' => 1, 'akhir_ayat' => 46],
            ['juz_id' => 25, 'nama_surat' => 'Fushshilat', 'mulai_ayat' => 47, 'akhir_ayat' => 54],
            ['juz_id' => 25, 'nama_surat' => 'Asy-Syura', 'mulai_ayat' => 1, 'akhir_ayat' => 53],
            ['juz_id' => 25, 'nama_surat' => 'Az-Zukhruf', 'mulai_ayat' => 1, 'akhir_ayat' => 89],
            ['juz_id' => 25, 'nama_surat' => 'Ad-Dukhan', 'mulai_ayat' => 1, 'akhir_ayat' => 59],
            ['juz_id' => 25, 'nama_surat' => 'Al-Jathiyah', 'mulai_ayat' => 1, 'akhir_ayat' => 37],
            ['juz_id' => 26, 'nama_surat' => 'Al-Ahqaf', 'mulai_ayat' => 1, 'akhir_ayat' => 35],
            ['juz_id' => 26, 'nama_surat' => 'Muhammad', 'mulai_ayat' => 1, 'akhir_ayat' => 38],
            ['juz_id' => 26, 'nama_surat' => 'Al-Fath', 'mulai_ayat' => 1, 'akhir_ayat' => 29],
            ['juz_id' => 26, 'nama_surat' => 'Al-Hujurat', 'mulai_ayat' => 1, 'akhir_ayat' => 18],
            ['juz_id' => 26, 'nama_surat' => 'Qaaf', 'mulai_ayat' => 1, 'akhir_ayat' => 45],
            ['juz_id' => 26, 'nama_surat' => 'Adz-Dzariyat', 'mulai_ayat' => 1, 'akhir_ayat' => 30],
            ['juz_id' => 27, 'nama_surat' => 'Adz-Dzariyat', 'mulai_ayat' => 31, 'akhir_ayat' => 60],
            ['juz_id' => 27, 'nama_surat' => 'At-Tur', 'mulai_ayat' => 1, 'akhir_ayat' => 49],
            ['juz_id' => 27, 'nama_surat' => 'An-Najm', 'mulai_ayat' => 1, 'akhir_ayat' => 62],
            ['juz_id' => 27, 'nama_surat' => 'Al-Qamar', 'mulai_ayat' => 1, 'akhir_ayat' => 55],
            ['juz_id' => 27, 'nama_surat' => 'Ar-Rahman', 'mulai_ayat' => 1, 'akhir_ayat' => 78],
            ['juz_id' => 27, 'nama_surat' => 'Al-Waqi\'ah', 'mulai_ayat' => 1, 'akhir_ayat' => 96],
            ['juz_id' => 27, 'nama_surat' => 'Al-Hadid', 'mulai_ayat' => 1, 'akhir_ayat' => 29],
            ['juz_id' => 28, 'nama_surat' => 'Al-Mujadalah', 'mulai_ayat' => 1, 'akhir_ayat' => 22],
            ['juz_id' => 28, 'nama_surat' => 'Al-Hasyr', 'mulai_ayat' => 1, 'akhir_ayat' => 24],
            ['juz_id' => 28, 'nama_surat' => 'Al-Mumtahanah', 'mulai_ayat' => 1, 'akhir_ayat' => 13],
            ['juz_id' => 28, 'nama_surat' => 'As-Saff', 'mulai_ayat' => 1, 'akhir_ayat' => 14],
            ['juz_id' => 28, 'nama_surat' => 'Al-Jumu\'ah', 'mulai_ayat' => 1, 'akhir_ayat' => 11],
            ['juz_id' => 28, 'nama_surat' => 'Al-Munafiqun', 'mulai_ayat' => 1, 'akhir_ayat' => 11],
            ['juz_id' => 28, 'nama_surat' => 'At-Taghabun', 'mulai_ayat' => 1, 'akhir_ayat' => 18],
            ['juz_id' => 28, 'nama_surat' => 'At-Talaq', 'mulai_ayat' => 1, 'akhir_ayat' => 12],
            ['juz_id' => 28, 'nama_surat' => 'At-Tahrim', 'mulai_ayat' => 1, 'akhir_ayat' => 12],
            ['juz_id' => 29, 'nama_surat' => 'Al-Mulk', 'mulai_ayat' => 1, 'akhir_ayat' => 30],
            ['juz_id' => 29, 'nama_surat' => 'Al-Qalam', 'mulai_ayat' => 1, 'akhir_ayat' => 52],
            ['juz_id' => 29, 'nama_surat' => 'Al-Haqqah', 'mulai_ayat' => 1, 'akhir_ayat' => 52],
            ['juz_id' => 29, 'nama_surat' => 'Al-Ma\'arij', 'mulai_ayat' => 1, 'akhir_ayat' => 44],
            ['juz_id' => 29, 'nama_surat' => 'Nuh', 'mulai_ayat' => 1, 'akhir_ayat' => 28],
            ['juz_id' => 29, 'nama_surat' => 'Al-Jin', 'mulai_ayat' => 1, 'akhir_ayat' => 28],
            ['juz_id' => 29, 'nama_surat' => 'Al-Muzammil', 'mulai_ayat' => 1, 'akhir_ayat' => 20],
            ['juz_id' => 29, 'nama_surat' => 'Al-Muddatstsir', 'mulai_ayat' => 1, 'akhir_ayat' => 56],
            ['juz_id' => 29, 'nama_surat' => 'Al-Qiyamah', 'mulai_ayat' => 1, 'akhir_ayat' => 40],
            ['juz_id' => 29, 'nama_surat' => 'Al-Insan', 'mulai_ayat' => 1, 'akhir_ayat' => 31],
            ['juz_id' => 29, 'nama_surat' => 'Al-Mursalat', 'mulai_ayat' => 1, 'akhir_ayat' => 50],
            ['juz_id' => 30, 'nama_surat' => 'An-Naba\'', 'mulai_ayat' => 1, 'akhir_ayat' => 40],
            ['juz_id' => 30, 'nama_surat' => 'An-Nazi\'at', 'mulai_ayat' => 1, 'akhir_ayat' => 46],
            ['juz_id' => 30, 'nama_surat' => '\'Abasa', 'mulai_ayat' => 1, 'akhir_ayat' => 42],
            ['juz_id' => 30, 'nama_surat' => 'At-Takwir', 'mulai_ayat' => 1, 'akhir_ayat' => 29],
            ['juz_id' => 30, 'nama_surat' => 'Al-Infithar', 'mulai_ayat' => 1, 'akhir_ayat' => 19],
            ['juz_id' => 30, 'nama_surat' => 'Al-Mutaffifin', 'mulai_ayat' => 1, 'akhir_ayat' => 36],
            ['juz_id' => 30, 'nama_surat' => 'Al-Insyiqaq', 'mulai_ayat' => 1, 'akhir_ayat' => 25],
            ['juz_id' => 30, 'nama_surat' => 'Al-Buruj', 'mulai_ayat' => 1, 'akhir_ayat' => 22],
            ['juz_id' => 30, 'nama_surat' => 'Al-Tariq', 'mulai_ayat' => 1, 'akhir_ayat' => 17],
            ['juz_id' => 30, 'nama_surat' => 'Al-A\'la', 'mulai_ayat' => 1, 'akhir_ayat' => 19],
            ['juz_id' => 30, 'nama_surat' => 'Al-Ghasyiyah', 'mulai_ayat' => 1, 'akhir_ayat' => 26],
            ['juz_id' => 30, 'nama_surat' => 'Al-Fajr', 'mulai_ayat' => 1, 'akhir_ayat' => 30],
            ['juz_id' => 30, 'nama_surat' => 'Al-Balad', 'mulai_ayat' => 1, 'akhir_ayat' => 20],
            ['juz_id' => 30, 'nama_surat' => 'Asy-Syams', 'mulai_ayat' => 1, 'akhir_ayat' => 15],
            ['juz_id' => 30, 'nama_surat' => 'Al-Lail', 'mulai_ayat' => 1, 'akhir_ayat' => 21],
            ['juz_id' => 30, 'nama_surat' => 'Adh-Dhuha', 'mulai_ayat' => 1, 'akhir_ayat' => 11],
            ['juz_id' => 30, 'nama_surat' => 'Al-Insyirah', 'mulai_ayat' => 1, 'akhir_ayat' => 8],
            ['juz_id' => 30, 'nama_surat' => 'At-Tin', 'mulai_ayat' => 1, 'akhir_ayat' => 8],
            ['juz_id' => 30, 'nama_surat' => 'Al-\'Alaq', 'mulai_ayat' => 1, 'akhir_ayat' => 19],
            ['juz_id' => 30, 'nama_surat' => 'Al-Qadr', 'mulai_ayat' => 1, 'akhir_ayat' => 5],
            ['juz_id' => 30, 'nama_surat' => 'Al-Bayyinah', 'mulai_ayat' => 1, 'akhir_ayat' => 8],
            ['juz_id' => 30, 'nama_surat' => 'Al-Zalzalah', 'mulai_ayat' => 1, 'akhir_ayat' => 8],
            ['juz_id' => 30, 'nama_surat' => 'Al-\'Adiyat', 'mulai_ayat' => 1, 'akhir_ayat' => 11],
            ['juz_id' => 30, 'nama_surat' => 'Al-Qari\'ah', 'mulai_ayat' => 1, 'akhir_ayat' => 11],
            ['juz_id' => 30, 'nama_surat' => 'At-Takatsur', 'mulai_ayat' => 1, 'akhir_ayat' => 8],
            ['juz_id' => 30, 'nama_surat' => 'Al-\'Ashr', 'mulai_ayat' => 1, 'akhir_ayat' => 3],
            ['juz_id' => 30, 'nama_surat' => 'Al-Humazah', 'mulai_ayat' => 1, 'akhir_ayat' => 9],
            ['juz_id' => 30, 'nama_surat' => 'Al-Fil', 'mulai_ayat' => 1, 'akhir_ayat' => 5],
            ['juz_id' => 30, 'nama_surat' => 'Al-Quraisy', 'mulai_ayat' => 1, 'akhir_ayat' => 4],
            ['juz_id' => 30, 'nama_surat' => 'Al-Ma\'un', 'mulai_ayat' => 1, 'akhir_ayat' => 7],
            ['juz_id' => 30, 'nama_surat' => 'Al-Kautsar', 'mulai_ayat' => 1, 'akhir_ayat' => 3],
            ['juz_id' => 30, 'nama_surat' => 'Al-Kafirun', 'mulai_ayat' => 1, 'akhir_ayat' => 6],
            ['juz_id' => 30, 'nama_surat' => 'An-Nashr', 'mulai_ayat' => 1, 'akhir_ayat' => 3],
            ['juz_id' => 30, 'nama_surat' => 'Al-Lahab', 'mulai_ayat' => 1, 'akhir_ayat' => 5],
            ['juz_id' => 30, 'nama_surat' => 'Al-Ikhlas', 'mulai_ayat' => 1, 'akhir_ayat' => 4],
            ['juz_id' => 30, 'nama_surat' => 'Al-Falaq', 'mulai_ayat' => 1, 'akhir_ayat' => 5],
            ['juz_id' => 30, 'nama_surat' => 'An-Nas', 'mulai_ayat' => 1, 'akhir_ayat' => 6],
        ];

        foreach ($surats as $surat) {
            Surat::create($surat);
        }
    }
}
